AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PokerTool Serverless Backend

Globals:
  Function:
    Timeout: 10


Resources:
  HttpApiCorsConfig:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - "content-type"
        AllowMethods:
          - OPTIONS
          - HEAD
          - POST
          - PUT
          - GET
        AllowOrigins:
          - "http://localhost:8000"

  createRoom:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: room.createRoom
      Runtime: nodejs18.x
      MemorySize: 512
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PokertoolTable
      Events:
        CreateRoom:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiCorsConfig
            Path: /rooms
            Method: post

  PokertoolTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pokertool
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
